Get available next ticket status #7
surrealist/dev-dynamo pull request #23
Opened 2023-06-30 05:55 UTC by JoJoushi

Get available next ticket status #7

2023-06-30 06:17 UTC, surrealist commented on DevDynamo.Web/Areas/ApiV1/Controllers/TicketController.cs
> +            var workFlowsSteps = db.WorkflowSteps.Where(x => x.ProjectId == ticket.ProjectId && x.ToStatus == ticket.Status).
ต้องเป็น `x.FromStatus == ticket.Status` นะครับ

2023-06-30 06:35 UTC, JoJoushi reviewed
เเก้ไข ToStatus เป็น FromStatus ครับ

2023-07-02 05:43 UTC, surrealist requested changes

2023-07-02 05:43 UTC, surrealist commented on DevDynamo.Web/Areas/ApiV1/Controllers/TicketsController.cs
> +            return workFlowsSteps;
รบกวนปรับ return objects ตาม response payload ใหม่ที่ comment ใน issue ด้วยคับ

2023-07-02 05:43 UTC, surrealist commented on DevDynamo.Web/Areas/ApiV1/Models/TicketNextStatusResponse.cs
> +    public string ToStatus { get; set; } = null!;
ขอปรับ `ToStatus` เป็น `NextStatus`

2023-07-02 05:43 UTC, surrealist commented on DevDynamo.Web/Areas/ApiV1/Controllers/TicketsController.cs
> +                return AppNotFound($"Ticket is not found");
เพิ่ม ticket id ด้วยครับ

2023-07-02 05:43 UTC, surrealist commented on DevDynamo.Models/WorkflowStep.cs
> +    public Guid ProjectId { get; set; }
ถ้ามี property นี้ (Guid) ต้องมี migrations ไหมครับ?

2023-07-02 05:43 UTC, surrealist commented on DevDynamo.Web/DevDynamo.Web.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="6.0.18" />
surrealist/develop ปัจจุบันเป็น 6.0.18 แล้ว ลอง sync อีกทีครับ

2023-07-08 03:15 UTC, surrealist approved these changes

2023-07-08 03:44 UTC, merged