DD-28
surrealist/dev-dynamo pull request #41
Opened 2023-07-06 05:08 UTC by armshare

2023-07-06 11:25 UTC, surrealist requested changes

2023-07-06 11:25 UTC, surrealist commented on DevDynamo.Web/Areas/ApiV1/Controllers/SystemController.cs
> +            var envi = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
We should use the `EnvironmentName` of the `IWebHostEnvironment` injected into the controller. 

Access to the environment variable might not be correct in every case.

2023-07-06 11:25 UTC, surrealist commented on DevDynamo.Web/Areas/ApiV1/Controllers/SystemController.cs
> +            string now = utcTime.ToString($"yyyy-MM-dd HH:mm:ss{localTime}");
combine UTC date/time with the timezone of the local. I don't think it's correct. 🤔

2023-07-06 11:25 UTC, surrealist commented on DevDynamo.Web/Areas/ApiV1/Models/SystemResponse.cs
> +    public string? now { get; set; }
We should name properties with CamelCase as it is a C# code. When it has returned from the API, it'll be converted to camelCase automatically.

2023-07-06 11:27 UTC, surrealist commented
Why this PR has so many commits? You might need an updated upstream version.

2023-07-06 15:34 UTC, armshare commented on DevDynamo.Web/Areas/ApiV1/Controllers/SystemController.cs
> +            string now = utcTime.ToString($"yyyy-MM-dd HH:mm:ss{localTime}");
ผมลองใช้ ทั้ง 
```
string utcTime = DateTime.UtcNow.ToString($"yyyy-MM-dd HH:mmzzz"); //2023-07-06 15:32+00:00
string localTime = DateTime.Now.ToString($"yyyy-MM-dd HH:mmzzz"); //2023-07-06 22:32+07:00
```
หรือมันมีมากกว่านี้อ่ะครับ

2023-07-07 12:04 UTC, surrealist commented
Thanks for the update. Let's talk tmr.

2023-07-08 03:12 UTC, surrealist approved these changes

2023-07-08 03:13 UTC, merged